### ISSUE TITLE
Rework kubernetes settings

### ISSUE THREAD

**Issue by mattfarina** [mattfarina/rd#89]
<img width="1052" alt="Screen Shot 2021-01-29 at 5 56 56 PM" src="https://user-images.githubusercontent.com/62991/106336026-011b1f00-625c-11eb-9f93-dbd72e4508e2.png">

**Comment by ericpromislow** [comment]
Fixed with merge of #98 - commit b6fd227 with a tweak fix in commit 0c0deea
