### ISSUE TITLE
Fix linking of binaries

### ISSUE THREAD

**Issue by mattfarina** [mattfarina/rd#91]
There are two issues with linking Helm and kubectl into the path...

1. It's not discovering paths that were previously linked. See https://github.com/mattfarina/rd/pull/82#pullrequestreview-579679412
2. If you opt-out of linking them into your path they will be re-linked on the next run.

**Comment by ericpromislow** [comment]
Ah, I missed the "first run" part of issue #50

**Comment by ericpromislow** [comment]
Fixed merging PR #94 in commit b4d1e30
